'use client'

import SideBar from "../components/SideBar"
import Player from "../components/Player"
import '../styles/globals.css'
import { RecoilRoot } from "recoil"


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <RecoilRoot>
      <html lang="en">
        <head />
        <body>
          <div className="bg-black h-screen overflow-hidden ">
            <div className='flex' >
              <SideBar />
              <div className='flex-1'>{children}</div>
            </div>
            <div className='sticky bottom-0'> <Player /></div>
          </div>
        </body>
      </html>
    </RecoilRoot>
  )
}
