'use client'
import SideBar from "../components/SideBar"
import Player from "../components/Player"
import '../styles/globals.css'
import { RecoilRoot } from "recoil"
import LoginPage from "../components/LoginSignUp"
import { useAuthState } from 'react-firebase-hooks/auth';
import { auth } from "../firebase";
import AppHeader from "../components/AppHeader"
import UserMsg from "../components/UserMsg"



export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  const [user, loading, error] = useAuthState(auth);



  return (
    <RecoilRoot>
      <html lang="en" className="overflow-hidden">
        <head />
        <body className="">
          {
            !user && !loading ? <LoginPage />
              :
              <>
                <main className="bg-black h-screen  flex   ">
                  <SideBar user={user} />
                  <div className='flex flex-col w-full ' >
                    <AppHeader user={user} />
                    <div className='flex-1 '>
                      {children}
                    </div>
                  </div>
                </main>
                <div className='sticky bottom-0'> <Player /></div>
                <UserMsg />
              </>
          }
        </body>
      </html>
    </RecoilRoot>
  )
}
